language: php
php:
  - 5.5
  - 5.4

install:
  - composer self-update
  - composer install

before_script: composer require task/cli ~0.1

script: vendor/bin/task test

after_script: vendor/bin/coveralls -v
